name: Publish Chrome Extension

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  
  workflow_dispatch:  # Allows manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Update manifest version
        run: |
          # Extract version from git tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Version: $VERSION"
          
          # Update manifest.json version
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" manifest.json
          
          # Verify version update
          grep "version" manifest.json
      
      - name: Create extension zip
        run: |
          zip -r plastic-extension.zip \
            manifest.json \
            popup.html \
            popup.js \
            content.js \
            styles.css \
            README.md \
            -x "*.git*" "node_modules/*" ".github/*"
          
          # Verify zip contents
          unzip -l plastic-extension.zip
      
      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: plastic-extension.zip
          extension-id: jmgohdfjidehbaggidpjikmccilopgpk
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          publish: false  # Set to true for auto-publish after upload
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Plastic v${{ github.ref_name }}
          body: |
            ## 🎨 Plastic v${{ github.ref_name }} - Enhanced Pixelization
            
            ### ✨ New Features
            - **Unlimited scaling** up to 1000% for detailed pixel art work
            - **Fine pixelization** down to 1px for precision control
            - **Configuration sharing** system for r/place team coordination
            - **Drag anywhere** on overlay (not just handle)
            - **Dynamic pixel grid** overlay for perfect alignment
            
            ### 🎯 Perfect for r/place & wplace
            - Share overlay configs with teammates via copy/paste codes
            - Coordinate large pixel art projects with identical setups
            - Enhanced pixelization for better reference matching
            
            ### 📦 Installation
            - **Chrome Web Store**: [Install Here](https://chrome.google.com/webstore/detail/jmgohdfjidehbaggidpjikmccilopgpk)
            - **Manual Install**: Download `plastic-extension.zip` from this release
            
            🤖 Generated with automated CI/CD pipeline
          files: plastic-extension.zip
          draft: false
          prerelease: false